modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"
issueTrackerURL="https://github.com/FTBTeam/FTB-Chunks/issues"

[[mods]]
modId="tacticalmap"
version="${version}"
displayName="Tactical Map"
authors="flowingsun"
description='''
Enhances FTB Chunks with team-based radar filtering and waypoint synchronization.
'''

[[dependencies.tacticalmap]]
modId="forge"
mandatory=true
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.tacticalmap]]
modId="ftbchunks"
mandatory=true
versionRange="[2001.3.6,)"
ordering="AFTER"
side="BOTH"

[[dependencies.tacticalmap]]
modId="ftbteams"
mandatory=true
versionRange="[2001.3.2,)"
ordering="AFTER"
side="BOTH"